name: DockerImage_v2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  prediction:
    runs-on: ubuntu-latest
    container: adsoft/ai-ops:latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install opencv,  pandas 
      run: pip install -r requirements.py
    
    - name: run linear model 
      run: python linear.py

    - name: run flowers model 
      run: python flowers.py

    - name: list models 
      run: ls -la 
      
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Download and run the Docker base image
      run: docker run -d --name serving_base tensorflow/serving
 
    - name: copy linear model to the Docker image
      run: docker cp ${{secrets.MODEL_NAME}} serving_base:/models/${{secrets.MODEL_NAME}}

    - name: copy flowers model to the Docker image
      run: docker cp ${{secrets.MODEL_NAME2}} serving_base:/models/${{secrets.MODEL_NAME2}}

    - name: show linear files in container
      run: docker exec serving_base ls -la models/${{secrets.MODEL_NAME}}/1

    - name: show flower files in container
      run: docker exec serving_base ls -la models/${{secrets.MODEL_NAME2}}/1

    - name: Build the custom Docker image
      run: docker commit --change "ENV MODEL_NAME ${{secrets.MODEL_NAME}}" serving_base ${{secrets.DOCKER_USER}}/tensorflow-${{secrets.MODEL_NAME}}:${{ github.sha }}

    - name: list Docker images
      run: docker images 
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/tensorflow-${{secrets.MODEL_NAME}}:${{ github.sha }}
